#!/bin/bash
 ssh azzab@52.226.70.235 -o StrictHostKeyChecking=no <<EOF              
 cd /home/azzab/Jenkins-nodejs  
 git pull       
 npm install --production       
 forever restart server.js
 exit       
EOF